---
- hosts: all
  sudo: yes
  tasks:
    - name:  install tools
      apt: name={{ item }} update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: install docker pgp key
      apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id=58118E89F3A912897C070ADBF76221572C52609D

    - name: docker apt src file
      lineinfile: create=true dest="/etc/apt/sources.list.d/docker.list" line="deb https://apt.dockerproject.org/repo ubuntu-trusty main"

    - name: apt install docker 
      apt: name=docker-engine update_cache=yes

    - name: start docker service
      service: name=docker enabled=yes state=started

    - name: add ezhuwya to docker group
      user: name=ezhuwya groups=docker,sudo

    - name: jenkins key
      command: sh -c 'wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key |  apt-key add -'

    - name: jenkins apt src
      command: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: install jenkins
      apt: name=jenkins update_cache=yes

